### ISSUE TITLE
importing packages

### ISSUE THREAD

**Issue by JasperSzkudlarski** [pxlit-projects/classroom-exercise-2-JasperSzkudlarski#1]
de imported packages van org.junit.* en org.springframework.* kunnen niet worden gevonden.
nu ik geloof dat het gradlew commando dit zou moeten oplossen?
maar die geeft een error: "Error: Could not find or load main class org.gradle.wrapper.GradleWrapperMain"
als ik hem run in mijn working directory, hetzelvde gebeurt bij de unix en bij de windows versie.

**Comment by Sch3lp** [comment]
Hmm.

Dan moet ge eens kijken of ge juist gecloned hebt. Misschien eens opnieuw clonen ofzo.

Want een medestudent heeft het ook al kunnen oplossen.

**Comment by JasperSzkudlarski** [comment]
nieuwe clone heeft hetzelvde probleem, probleem blijft op mn desktop en op mn laptop hetzelvde.

Nu het valt mij nu op dat er geen gradle-wrapper.jar is in de directory [project-name]/gradle/wrapper, niet in de repo en ook niet in mijn lokale versie.
En, in de build.gradle staat er ook geen:
`task wrapper(type: Wrapper) {
    gradleVersion = '3.1'
}`
dit staat we in de build.gradle van de eerste oefening.

references die ik nodig had om deze mogelijke problemen te identificeren:
https://www.mkyong.com/gradle/jenkins-could-not-find-gradlewrappermain/
http://stackoverflow.com/questions/29805622/could-not-find-or-load-main-class-org-gradle-wrapper-gradlewrappermain

**Comment by Sch3lp** [comment]
Die medestudent had een lokale Gradle install, vandaar dat dat bij hem wel gewoon werkte.

**Comment by Sch3lp** [comment]
Om het rap te fixen kunt ge die gradle-wrapper.jar vanuit de vorige exercise kopieren.

**Comment by JasperSzkudlarski** [comment]
nice, werkt.
